/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/app';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/http';
import * as import5 from '@angular/forms';
import * as import6 from '../../../app/redditImageSearch';
import * as import7 from './reddit.component.ngfactory';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _APP_INITIALIZER_2:any[];
  _ApplicationInitStatus_3:import0.ApplicationInitStatus;
  _ɵf_4:import0.ɵf;
  _ApplicationRef_5:any;
  _ApplicationModule_6:import0.ApplicationModule;
  _BrowserModule_7:import3.BrowserModule;
  _HttpModule_8:import4.HttpModule;
  _ɵba_9:import5.ɵba;
  _ReactiveFormsModule_10:import5.ReactiveFormsModule;
  _AppModule_11:import1.AppModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import2.NgLocaleLocalization;
  __Compiler_14:import0.Compiler;
  __APP_ID_15:any;
  __IterableDiffers_16:any;
  __KeyValueDiffers_17:any;
  __DomSanitizer_18:import3.ɵe;
  __Sanitizer_19:any;
  __HAMMER_GESTURE_CONFIG_20:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import3.EventManager;
  __ɵDomSharedStylesHost_23:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_24:import3.ɵDomRendererFactory2;
  __RendererFactory2_25:any;
  __ɵSharedStylesHost_26:any;
  __Testability_27:import0.Testability;
  __Meta_28:import3.Meta;
  __Title_29:import3.Title;
  __BrowserXhr_30:import4.BrowserXhr;
  __ResponseOptions_31:import4.BaseResponseOptions;
  __XSRFStrategy_32:any;
  __XHRBackend_33:import4.XHRBackend;
  __RequestOptions_34:import4.BaseRequestOptions;
  __Http_35:any;
  __FormBuilder_36:import5.FormBuilder;
  __ɵi_37:import5.ɵi;
  __RedditImageSearch_38:import6.RedditImageSearch;
  constructor(parent:import0.Injector) {
    super(parent,[import7.RedditComponentNgFactory],[import7.RedditComponentNgFactory]);
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == null)) { (this.__LOCALE_ID_12 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == null)) { (this.__NgLocalization_13 = new import2.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _Compiler_14():import0.Compiler {
    if ((this.__Compiler_14 == null)) { (this.__Compiler_14 = new import0.Compiler()); }
    return this.__Compiler_14;
  }
  get _APP_ID_15():any {
    if ((this.__APP_ID_15 == null)) { (this.__APP_ID_15 = import0.ɵg()); }
    return this.__APP_ID_15;
  }
  get _IterableDiffers_16():any {
    if ((this.__IterableDiffers_16 == null)) { (this.__IterableDiffers_16 = import0.ɵl()); }
    return this.__IterableDiffers_16;
  }
  get _KeyValueDiffers_17():any {
    if ((this.__KeyValueDiffers_17 == null)) { (this.__KeyValueDiffers_17 = import0.ɵm()); }
    return this.__KeyValueDiffers_17;
  }
  get _DomSanitizer_18():import3.ɵe {
    if ((this.__DomSanitizer_18 == null)) { (this.__DomSanitizer_18 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_18;
  }
  get _Sanitizer_19():any {
    if ((this.__Sanitizer_19 == null)) { (this.__Sanitizer_19 = this._DomSanitizer_18); }
    return this.__Sanitizer_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == null)) { (this.__HAMMER_GESTURE_CONFIG_20 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == null)) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import3.EventManager {
    if ((this.__EventManager_22 == null)) { (this.__EventManager_22 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import0.NgZone))); }
    return this.__EventManager_22;
  }
  get _ɵDomSharedStylesHost_23():import3.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_23 == null)) { (this.__ɵDomSharedStylesHost_23 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_23;
  }
  get _ɵDomRendererFactory2_24():import3.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_24 == null)) { (this.__ɵDomRendererFactory2_24 = new import3.ɵDomRendererFactory2(this._EventManager_22,this._ɵDomSharedStylesHost_23)); }
    return this.__ɵDomRendererFactory2_24;
  }
  get _RendererFactory2_25():any {
    if ((this.__RendererFactory2_25 == null)) { (this.__RendererFactory2_25 = this._ɵDomRendererFactory2_24); }
    return this.__RendererFactory2_25;
  }
  get _ɵSharedStylesHost_26():any {
    if ((this.__ɵSharedStylesHost_26 == null)) { (this.__ɵSharedStylesHost_26 = this._ɵDomSharedStylesHost_23); }
    return this.__ɵSharedStylesHost_26;
  }
  get _Testability_27():import0.Testability {
    if ((this.__Testability_27 == null)) { (this.__Testability_27 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_27;
  }
  get _Meta_28():import3.Meta {
    if ((this.__Meta_28 == null)) { (this.__Meta_28 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_28;
  }
  get _Title_29():import3.Title {
    if ((this.__Title_29 == null)) { (this.__Title_29 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_29;
  }
  get _BrowserXhr_30():import4.BrowserXhr {
    if ((this.__BrowserXhr_30 == null)) { (this.__BrowserXhr_30 = new import4.BrowserXhr()); }
    return this.__BrowserXhr_30;
  }
  get _ResponseOptions_31():import4.BaseResponseOptions {
    if ((this.__ResponseOptions_31 == null)) { (this.__ResponseOptions_31 = new import4.BaseResponseOptions()); }
    return this.__ResponseOptions_31;
  }
  get _XSRFStrategy_32():any {
    if ((this.__XSRFStrategy_32 == null)) { (this.__XSRFStrategy_32 = import4.ɵb()); }
    return this.__XSRFStrategy_32;
  }
  get _XHRBackend_33():import4.XHRBackend {
    if ((this.__XHRBackend_33 == null)) { (this.__XHRBackend_33 = new import4.XHRBackend(this._BrowserXhr_30,this._ResponseOptions_31,this._XSRFStrategy_32)); }
    return this.__XHRBackend_33;
  }
  get _RequestOptions_34():import4.BaseRequestOptions {
    if ((this.__RequestOptions_34 == null)) { (this.__RequestOptions_34 = new import4.BaseRequestOptions()); }
    return this.__RequestOptions_34;
  }
  get _Http_35():any {
    if ((this.__Http_35 == null)) { (this.__Http_35 = import4.ɵc(this._XHRBackend_33,this._RequestOptions_34)); }
    return this.__Http_35;
  }
  get _FormBuilder_36():import5.FormBuilder {
    if ((this.__FormBuilder_36 == null)) { (this.__FormBuilder_36 = new import5.FormBuilder()); }
    return this.__FormBuilder_36;
  }
  get _ɵi_37():import5.ɵi {
    if ((this.__ɵi_37 == null)) { (this.__ɵi_37 = new import5.ɵi()); }
    return this.__ɵi_37;
  }
  get _RedditImageSearch_38():import6.RedditImageSearch {
    if ((this.__RedditImageSearch_38 == null)) { (this.__RedditImageSearch_38 = new import6.RedditImageSearch(this._Http_35)); }
    return this.__RedditImageSearch_38;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import3.ɵa();
    this._APP_INITIALIZER_2 = [
      import0.ɵo,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_3 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_2);
    this._ɵf_4 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_3);
    this._ApplicationRef_5 = this._ɵf_4;
    this._ApplicationModule_6 = new import0.ApplicationModule(this._ApplicationRef_5);
    this._BrowserModule_7 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._HttpModule_8 = new import4.HttpModule();
    this._ɵba_9 = new import5.ɵba();
    this._ReactiveFormsModule_10 = new import5.ReactiveFormsModule();
    this._AppModule_11 = new import1.AppModule();
    return this._AppModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_2; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_3; }
    if ((token === import0.ɵf)) { return this._ɵf_4; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_5; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_6; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_7; }
    if ((token === import4.HttpModule)) { return this._HttpModule_8; }
    if ((token === import5.ɵba)) { return this._ɵba_9; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_10; }
    if ((token === import1.AppModule)) { return this._AppModule_11; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import0.Compiler)) { return this._Compiler_14; }
    if ((token === import0.APP_ID)) { return this._APP_ID_15; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_16; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_17; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_18; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_19; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import3.EventManager)) { return this._EventManager_22; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_23; }
    if ((token === import3.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_24; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_25; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_26; }
    if ((token === import0.Testability)) { return this._Testability_27; }
    if ((token === import3.Meta)) { return this._Meta_28; }
    if ((token === import3.Title)) { return this._Title_29; }
    if ((token === import4.BrowserXhr)) { return this._BrowserXhr_30; }
    if ((token === import4.ResponseOptions)) { return this._ResponseOptions_31; }
    if ((token === import4.XSRFStrategy)) { return this._XSRFStrategy_32; }
    if ((token === import4.XHRBackend)) { return this._XHRBackend_33; }
    if ((token === import4.RequestOptions)) { return this._RequestOptions_34; }
    if ((token === import4.Http)) { return this._Http_35; }
    if ((token === import5.FormBuilder)) { return this._FormBuilder_36; }
    if ((token === import5.ɵi)) { return this._ɵi_37; }
    if ((token === import6.RedditImageSearch)) { return this._RedditImageSearch_38; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_4.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_23 && this._ɵDomSharedStylesHost_23.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlndS9Eb3dubG9hZHMvYW5ndWxhci1hb3QtZXMyMDE1LXJvbGx1cC9zcmMvYXBwL2FwcC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jaHJpZ3UvRG93bmxvYWRzL2FuZ3VsYXItYW90LWVzMjAxNS1yb2xsdXAvc3JjL2FwcC9hcHAudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
